#!/bin/bash

set -o errexit

# Add chmod aliases
chmodf() { find $2 -type f -exec chmod -v $1 {} \;
}
chmodd() { find $2 -type d -exec chmod -v $1 {} \;
}

# If DataDirectory, identity keys or anonrc is mounted here,
# ownership needs to be changed to the ANON_USER user
chown -Rv ${ANON_USER}:${ANON_USER} /var/lib/anon

# Fix permissions
chmodd 700 /var/lib/anon
chmodf 600 /var/lib/anon

if [ ! -e /tor-config-done ]; then
    # Run this only once
    touch /tor-config-done

    if [ ! -f /etc/anon/anonrc ]; then
        cp /etc/anonrc /etc/anon/

        # Add Address from env variable
        echo "Setting Contact Email: ${IP_ADDRESS}"
        echo -e "\nAddress ${IP_ADDRESS}" >> /etc/anon/anonrc

        # Add Nickname from env variable
        echo "Setting chosen Nickname: ${ANON_NICKNAME}"
        echo -e "\nNickname ${ANON_NICKNAME}" >> /etc/anon/anonrc

        # Add ContactInfo from env variable
        echo "Setting Contact Email: ${CONTACT_EMAIL}"
        echo -e "\nContactInfo ${CONTACT_EMAIL}" >> /etc/anon/anonrc
    fi

    # Generate keys
    KEYPATH=/var/lib/anon/keys
    if [ ! -f ${KEYPATH}/authority_identity_key ]; then
        mkdir -p ${KEYPATH}
        echo "password" | anon-gencert --create-identity-key \
            -i ${KEYPATH}/authority_identity_key \
            -s ${KEYPATH}/authority_signing_key \
            -c ${KEYPATH}/authority_certificate \
            --passphrase-fd 0
    fi
    
fi

# Display OS version, Tor version & anonrc in log
echo -e "Debian Version: \c" && cat /etc/debian_version
tor --version
cat /etc/anon/anonrc

# else default to run whatever the user wanted like "bash"
exec "$@"
