name: Build Anon Client for Linux
description: Builds the Anon client for Linux and uploads the executables as an artifact.
inputs:
  build-arch:
    required: true
    description: The architecture to build for (amd64 or arm64).
  lib-arch:
    required: true
    description: The architecture for the libraries (x86_64 or aarch64).
  release-phase:
    required: true
    description: The release phase (beta, live, stage, dev, or unstable-dev).
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        apt-get update && \
        apt_build_deps="libssl-dev zlib1g-dev libevent-dev ca-certificates dh-apparmor libseccomp-dev debhelper" && \
        apt_runtime_deps="iputils-ping curl pwgen" && \
        apt_temps="build-essential automake git wget" && \
        apt-get -y --no-install-recommends install $apt_build_deps $apt_runtime_deps $apt_temps
    - name: Build anon
      shell: bash
      run: |
        ./scripts/ci/update-env.sh ${{ inputs.release-phase }}
        ./autogen.sh
        ./configure \
          --disable-asciidoc \
          --disable-zstd \
          --disable-lzma \
          --enable-static-zlib \
          --enable-static-libevent \
          --enable-static-openssl \
          --enable-static-tor \
          --with-libevent-dir=/usr/lib/${{ inputs.lib-arch }}-linux-gnu/ \
          --with-openssl-dir=/usr/lib/${{ inputs.lib-arch }}-linux-gnu/ \
          --with-zlib-dir=/usr/lib/${{ inputs.lib-arch }}-linux-gnu/ \
          --disable-tool-name-check \
          --disable-gcc-hardening
        make
    - name: Copy executables to artifact directory
      shell: bash
      run: |
        mkdir -p package
        cp src/app/anon package
        cp src/tools/anon-gencert package
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: anon-${{ inputs.release-phase }}-linux-${{ inputs.build-arch }}
        path: package/