#!/bin/bash

set -o errexit

# Add chmod aliases
chmodf() { find $2 -type f -exec chmod -v $1 {} \;
}
chmodd() { find $2 -type d -exec chmod -v $1 {} \;
}

# If DataDirectory, identity keys or anonrc is mounted here,
# ownership needs to be changed to the TOR_USER user
chown -Rv ${TOR_USER}:${TOR_USER} /var/lib/tor

# Fix permissions
chmodd 700 /var/lib/tor
chmodf 600 /var/lib/tor

if [ ! -e /tor-config-done ]; then
    # Run this only once
    touch /tor-config-done

    # Add Nickname from env variable or randomized, if none has been set
    if ! grep -q '^Nickname ' /etc/tor/anonrc; then
        if [ ${TOR_NICKNAME} == "ATORv4" ] || [ -z "${TOR_NICKNAME}" ]; then
            # if user did not change the default nickname, genetrate a random pronounceable one
            RPW=$(pwgen -0A 8)
            TOR_NICKNAME="ATORv4${RPW}"
            echo "Setting random Nickname: ${TOR_NICKNAME}"
        else
            echo "Setting chosen Nickname: ${TOR_NICKNAME}"
        fi
        echo -e "\nNickname ${TOR_NICKNAME}" >> /etc/tor/anonrc
    fi

    # Add Contact_Email from env variable, if none has been set in anonrc
    if ! grep -q '^ContactInfo ' /etc/tor/anonrc; then
        # if CONTACT_EMAIL is not null
        if [ -n "${CONTACT_EMAIL}" ]; then
            echo "Setting Contact Email: ${CONTACT_EMAIL}"
            echo -e "\nContactInfo ${CONTACT_EMAIL}" >> /etc/tor/anonrc
        fi
    fi
fi

# Display OS version, Tor version & anonrc in log
echo -e "Debian Version: \c" && cat /etc/debian_version
tor --version
cat /etc/tor/anonrc

# else default to run whatever the user wanted like "bash"
exec "$@"
