#!/bin/sh

# systemd generator to create dependency symlink to start
# all anon instances from /etc/anon/instances/

set -eu

if [ $# -lt 1 ]; then
    echo >&2 "Usage: $0 <wantdir> [...]"
    exit 1
fi

GENDIR="$1"
WANTDIR="$1/anon.service.wants"
SERVICEFILE="/lib/systemd/system/anon@.service"
DEFAULTTOR="/lib/systemd/system/anon@default.service"
BASEETC="/etc/anon/instances"

mkdir -p "$WANTDIR"

[ -e "/etc/anon/anonrc" ] && ln -s "$DEFAULTTOR" "$WANTDIR/"
for name in $( find "$BASEETC" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' ); do
    if echo "x$name" | grep -q '[^a-zA-Z0-9]' ||
       [ "$name" = "default" ] ; then
        continue
    fi
    [ -e "$BASEETC/$name/anonrc" ] && ln -s "$SERVICEFILE" "$WANTDIR/anon@$name.service"
done

exit 0

