name: Live Build Image and Deploy

on:
  push:
    tags:
      - 'v*.*.*.*'
  workflow_dispatch:

env:
  image-name: ghcr.io/anyone-protocol/ator-protocol
  image-tag: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      matrix:
        platform:
          - name: linux/amd64
            image-suffix: amd64
            runs-on: ubuntu-latest
          - name: linux/arm64
            image-suffix: arm64
            runs-on: arm64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          docker-base-repo: ${{ env.image-name }}-${{ matrix.platform.image-suffix }}
          docker-tag: ${{ env.image-tag }}
          docker-platform: ${{ matrix.platform.name }}
          version: ${{ github.sha }}
          environment: live
          event-name: ${{ github.event_name }}

  multiarch-push:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Multiarch push
        uses: ./.github/actions/multiarch-push
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          docker-base-repo: ${{ env.image-name }}
          docker-tag: ${{ env.image-tag }}
          event-name: ${{ github.event_name }}

  deploy:
    if: ${{ !contains(github.ref, 'beta') }}
    needs: multiarch-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Deploy new version
        uses: ./.github/actions/deploy
        with:
          image-tag: ${{ env.image-tag }}
          nomad-job-file: anon-da-node-live.hcl
          nomad-cacert: operations/admin-ui-ca.crt
          nomad-token: ${{ secrets.NOMAD_TOKEN_ATOR_NETWORK_DEPLOY }}
          nomad-addr: ${{ secrets.NOMAD_DEPLOY_ADDR }}
          consul-cacert: operations/admin-ui-ca.crt
          consul-http-token: ${{ secrets.CONSUL_HTTP_TOKEN_ATOR_NETWORK_DEPLOY }}
          consul-addr: ${{ secrets.CONSUL_DEPLOY_ADDR }}
